package com.congviechangngay.pro

import android.content.Context
import android.content.Intent
import android.net.Uri
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.compose.setContent
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.core.content.FileProvider
import java.io.File

class MainActivity:ComponentActivity(){override fun onCreate(b:Bundle?){super.onCreate(b);setContent{App(this)}}}

@OptIn(ExperimentalMaterial3Api::class)
@Composable fun App(ctx:Context){
    val db=remember{AppDb(ctx)};val prefs=remember{ctx.getSharedPreferences("cvhn",Context.MODE_PRIVATE)}
    var shift by remember{mutableStateOf(prefs.getString("shift","")?:"")};var showShift by remember{mutableStateOf(shift.isBlank())};var tab by remember{mutableIntStateOf(0)};var refresh by remember{mutableIntStateOf(0)}
    val date=today();val tasks=remember(date,shift,refresh){if(shift.isBlank())emptyList()else db.tasks(date,shift)};val todos=remember(refresh){db.todos()};val overdue=todos.count{it.status!="HOÀN THÀNH"&&it.due.isNotBlank()&&it.due<date};val dueToday=todos.count{it.status!="HOÀN THÀNH"&&it.due==date}
    if(showShift)AlertDialog(onDismissRequest={},title={Text("Hôm nay bạn đi ca gì?")},text={Column{Shift.values().forEach{s->TextButton(onClick={shift=s.label;prefs.edit().putString("shift",shift).apply();showShift=false},modifier=Modifier.fillMaxWidth()){Text("${s.label}: %02d:00 - %02d:00".format(s.start,s.end))}}}},confirmButton={})
    Scaffold(topBar={TopAppBar(title={Text("Công việc Pro")},actions={TextButton(onClick={showShift=true}){Text(shift.ifBlank{"Chọn ca"})}})},bottomBar={NavigationBar{
        NavigationBarItem(tab==0,{tab=0},{},label={Text("Hôm nay")});NavigationBarItem(tab==1,{tab=1},{},label={Text("Nhắc việc")});NavigationBarItem(tab==2,{tab=2},{},label={Text("Nghiệp vụ")});NavigationBarItem(tab==3,{tab=3},{},label={Text("Lịch sử")});NavigationBarItem(tab==4,{tab=4},{},label={Text("Tổng quan")})
    }}){pad->when(tab){0->TodayScreen(ctx,db,shift,tasks,{refresh++});1->TodoScreen(ctx,db,todos,date,{refresh++});2->BusinessScreen(ctx,db,date,{refresh++});3->HistoryScreen(db,shift,refresh);else->OverviewScreen(tasks,todos,shift,overdue,dueToday)}}
}

@Composable fun TodayScreen(ctx:Context,db:AppDb,shift:String,tasks:List<DailyTask>,refresh:()->Unit){var selected by remember{mutableStateOf<DailyTask?>(null)};val done=tasks.count{it.status=="HOÀN THÀNH"};val doing=tasks.count{it.status=="ĐANG LÀM"};val bad=tasks.count{it.problem};Column(Modifier.fillMaxSize().padding(12.dp)){Card(Modifier.fillMaxWidth()){Column(Modifier.padding(16.dp)){Text("$shift • ${today()}",style=MaterialTheme.typography.titleMedium);Text("18 công việc • mặc định 30 phút/việc");Text("Hoàn thành: $done/18 • Đang làm: $doing • Có vấn đề: $bad");LinearProgressIndicator(progress={done/18f},modifier=Modifier.fillMaxWidth())}};Spacer(Modifier.height(8.dp));LazyColumn(verticalArrangement=Arrangement.spacedBy(8.dp)){items(tasks,key={it.id}){t->Card(Modifier.fillMaxWidth()){Row(Modifier.padding(8.dp),verticalAlignment=Alignment.CenterVertically){Checkbox(t.status=="HOÀN THÀNH",{v->db.updateTask(t.id,if(v)"HOÀN THÀNH" else "CHƯA LÀM",t.note,t.problem,t.started,if(v)System.currentTimeMillis() else null);refresh()});Column(Modifier.weight(1f)){Text("${t.number}. ${t.title}");Text("${t.status} • ${if(t.started!=null&&t.finished!=null)elapsed(t.started,t.finished) else "30 phút dự kiến"}")};TextButton(onClick={selected=t}){Text("Chi tiết")}}}}}};selected?.let{TaskDialog(ctx,db,it){selected=null;refresh()}}}

@Composable fun TaskDialog(ctx:Context,db:AppDb,t:DailyTask,close:()->Unit){var status by remember{mutableStateOf(t.status)};var note by remember{mutableStateOf(t.note)};var problem by remember{mutableStateOf(t.problem)};var photoUri by remember{mutableStateOf<Uri?>(null)};val launcher=rememberLauncherForActivityResult(ActivityResultContracts.TakePicture()){ok->if(ok){val uri=photoUri;if(uri!=null)db.addAttachment("TASK",t.id,uri.toString())}};AlertDialog(onDismissRequest=close,title={Text("Công việc ${t.number}")},text={Column{Text(t.title,style=MaterialTheme.typography.titleMedium);Text("Thời gian mặc định: ${t.minutes} phút");DropdownStatus(status){status=it};Row(verticalAlignment=Alignment.CenterVertically){Checkbox(problem,{problem=!problem});Text("Có vấn đề / cần theo dõi")};OutlinedTextField(note,{note=it},Modifier.fillMaxWidth(),label={Text("Ghi chú")});Button(onClick={val dir=File(ctx.filesDir,"images");dir.mkdirs();val file=File(dir,"${System.currentTimeMillis()}.jpg");val uri=FileProvider.getUriForFile(ctx,"com.congviechangngay.pro.fileprovider",file);photoUri=uri;launcher.launch(uri)},Modifier.fillMaxWidth()){Text("📷 Chụp ảnh")}}},confirmButton={Button(onClick={val now=System.currentTimeMillis();val st=if(status=="ĐANG LÀM"&&t.started==null)now else t.started;val fin=if(status=="HOÀN THÀNH")(t.finished?:now)else null;db.updateTask(t.id,status,note,problem,st,fin);close()}){Text("Lưu")}},dismissButton={TextButton(onClick=close){Text("Hủy")}})}
@Composable fun DropdownStatus(current:String,onChange:(String)->Unit){var open by remember{mutableStateOf(false)};Box{OutlinedButton(onClick={open=true}){Text("Trạng thái: $current")};DropdownMenu(expanded=open,onDismissRequest={open=false}){listOf("CHƯA LÀM","ĐANG LÀM","HOÀN THÀNH","CÓ VẤN ĐỀ","BỎ QUA").forEach{s->DropdownMenuItem(text={Text(s)},onClick={onChange(s);open=false})}}}}

@Composable fun TodoScreen(ctx:Context,db:AppDb,todos:List<Todo>,date:String,refresh:()->Unit){var title by remember{mutableStateOf("")};var detail by remember{mutableStateOf("")};var related by remember{mutableStateOf("")};var due by remember{mutableStateOf(date)};var priority by remember{mutableStateOf("BÌNH THƯỜNG")};var expanded by remember{mutableStateOf(false)};Column(Modifier.fillMaxSize().padding(12.dp)){Text("🔔 Nhắc việc & Tồn đọng",style=MaterialTheme.typography.headlineSmall);Text("Quá hạn: ${todos.count{it.status!="HOÀN THÀNH"&&it.due<date}} • Hôm nay: ${todos.count{it.status!="HOÀN THÀNH"&&it.due==date}}");OutlinedTextField(title,{title=it},Modifier.fillMaxWidth(),label={Text("Tiêu đề vấn đề")});OutlinedTextField(detail,{detail=it},Modifier.fillMaxWidth(),label={Text("Chi tiết")});OutlinedTextField(related,{related=it},Modifier.fillMaxWidth(),label={Text("Người / bộ phận liên quan")});OutlinedTextField(due,{due=it},Modifier.fillMaxWidth(),label={Text("Hạn YYYY-MM-DD")});Box{OutlinedButton(onClick={expanded=true}){Text("Mức độ: $priority")};DropdownMenu(expanded=expanded,onDismissRequest={expanded=false}){listOf("KHẨN CẤP","CAO","BÌNH THƯỜNG").forEach{s->DropdownMenuItem(text={Text(s)},onClick={priority=s;expanded=false})}}};Button(onClick={if(title.isNotBlank()){db.addTodo(Todo(0,title,detail,related,date,due,0,priority,"CHƯA XỬ LÝ"));title="";detail="";related="";due=date;priority="BÌNH THƯỜNG";refresh()}},Modifier.fillMaxWidth()){Text("Thêm tồn đọng")};Spacer(Modifier.height(8.dp));LazyColumn(verticalArrangement=Arrangement.spacedBy(8.dp)){items(todos,key={it.id}){TodoCard(ctx,db,it,date,refresh)}}}}
@Composable fun TodoCard(ctx:Context,db:AppDb,t:Todo,date:String,refresh:()->Unit){var progress by remember(t.id,t.progress){mutableFloatStateOf(t.progress.toFloat())};val late=t.status!="HOÀN THÀNH"&&t.due.isNotBlank()&&t.due<date;Card(Modifier.fillMaxWidth()){Column(Modifier.padding(12.dp)){Text(if(late)"🔴 QUÁ HẠN" else if(t.due==date&&t.status!="HOÀN THÀNH")"🟠 ĐẾN HẠN HÔM NAY" else "🟡 ${t.priority}");Text(t.title,style=MaterialTheme.typography.titleMedium);if(t.detail.isNotBlank())Text(t.detail);Text("${t.status} • Hạn: ${t.due.ifBlank{"Chưa đặt"}} • ${progress.toInt()}%");Slider(value=progress,onValueChange={progress=it},valueRange=0f..100f,steps=3);Row{Button(onClick={db.updateTodo(t.id,progress.toInt(),if(progress>=100)"HOÀN THÀNH" else "ĐANG XỬ LÝ");refresh()}){Text("Lưu tiến độ")};Spacer(Modifier.width(6.dp));OutlinedButton(onClick={shareText(ctx,"[CÔNG VIỆC HẰNG NGÀY]\n${t.title}\n${t.detail}\nHạn: ${t.due}\nTiến độ: ${progress.toInt()}%")}){Text("Chia sẻ")}}}}}

@Composable fun BusinessScreen(ctx:Context,db:AppDb,date:String,refresh:()->Unit){var module by remember{mutableStateOf<String?>(null)};Column(Modifier.fillMaxSize().padding(12.dp)){Text("📋 Nghiệp vụ",style=MaterialTheme.typography.headlineSmall);Text("Dữ liệu được lưu theo ngày, có thể chỉnh sửa và dùng offline.");Spacer(Modifier.height(8.dp));val items=listOf("👥 Nhân sự 2 nhóm" to "PERSON","⏱️ Làm thêm / OT" to "OT","📊 AMH" to "AMH","📦 Hàng xuất" to "SHIP","💾 Hàng DATA" to "DATA","📧 Chốt lô / báo cáo mail" to "LOT","✉️ Theo dõi mail" to "MAIL");items.forEach{(title,key)->Card(Modifier.fillMaxWidth().padding(bottom=8.dp)){Row(Modifier.padding(14.dp).fillMaxWidth(),verticalAlignment=Alignment.CenterVertically){Text(title,Modifier.weight(1f),style=MaterialTheme.typography.titleMedium);Button(onClick={module=key}){Text("Mở")}}}}};when(module){"PERSON"->PersonDialog(db,date,{module=null;refresh()});"OT"->OtDialog(db,date,{module=null;refresh()});"AMH"->AmhDialog(db,date,{module=null;refresh()});"SHIP"->ShipmentDialog(db,date,{module=null;refresh()});"DATA"->DataDialog(db,date,{module=null;refresh()});"LOT"->LotDialog(ctx,db,date,{module=null;refresh()});"MAIL"->MailDialog(ctx,db,date,{module=null;refresh()})}}

@Composable fun PersonDialog(db:AppDb,date:String,close:()->Unit){var name by remember{mutableStateOf("")};var group by remember{mutableStateOf("Nhóm 1")};var shift by remember{mutableStateOf("Ca sáng")};var ot by remember{mutableStateOf("0")};val list=db.personnel(date);SimpleDialog("👥 Nhân sự • $date",close){OutlinedTextField(name,{name=it},Modifier.fillMaxWidth(),label={Text("Họ tên / SBD")});OutlinedTextField(group,{group=it},Modifier.fillMaxWidth(),label={Text("Nhóm 1 / Nhóm 2")});OutlinedTextField(shift,{shift=it},Modifier.fillMaxWidth(),label={Text("Ca")});OutlinedTextField(ot,{ot=it},Modifier.fillMaxWidth(),label={Text("OT giờ")});Button(onClick={if(name.isNotBlank()){db.addPerson(Person(0,name,group,shift,date,ot.toDoubleOrNull()?:0.0));name=""}},Modifier.fillMaxWidth()){Text("Thêm nhân sự")};Text("Đã khai báo: ${list.size} người");list.takeLast(20).forEach{Text("• ${it.name} | ${it.groupName} | ${it.shift} | OT ${it.ot}h")}}}
@Composable fun OtDialog(db:AppDb,date:String,close:()->Unit){var name by remember{mutableStateOf("")};var hours by remember{mutableStateOf("")};var reason by remember{mutableStateOf("")};val list=db.ot(date);SimpleDialog("⏱️ Làm thêm / OT • $date",close){OutlinedTextField(name,{name=it},Modifier.fillMaxWidth(),label={Text("Họ tên / SBD")});OutlinedTextField(hours,{hours=it},Modifier.fillMaxWidth(),label={Text("Số giờ OT")});OutlinedTextField(reason,{reason=it},Modifier.fillMaxWidth(),label={Text("Lý do / công việc")});Button(onClick={if(name.isNotBlank()){db.addOt(OtRecord(0,date,name,hours.toDoubleOrNull()?:0.0,reason,"CHỜ KHAI"));name="";hours="";reason=""}},Modifier.fillMaxWidth()){Text("Thêm OT")};Text("Tổng OT: ${list.sumOf{it.hours}} giờ");list.forEach{Text("• ${it.name}: ${it.hours}h | ${it.status} | ${it.reason}")}}}
@Composable fun AmhDialog(db:AppDb,date:String,close:()->Unit){var code by remember{mutableStateOf("")};var qty by remember{mutableStateOf("")};var note by remember{mutableStateOf("")};val list=db.amh(date);SimpleDialog("📊 AMH • $date",close){OutlinedTextField(code,{code=it},Modifier.fillMaxWidth(),label={Text("Mã / công đoạn")});OutlinedTextField(qty,{qty=it},Modifier.fillMaxWidth(),label={Text("Số lượng")});OutlinedTextField(note,{note=it},Modifier.fillMaxWidth(),label={Text("Ghi chú")});Button(onClick={if(code.isNotBlank()){db.addAmh(AmhRecord(0,date,code,qty.toIntOrNull()?:0,note));code="";qty="";note=""}},Modifier.fillMaxWidth()){Text("Thêm AMH")};list.forEach{Text("• ${it.code}: ${it.qty} | ${it.note}")}}}
@Composable fun ShipmentDialog(db:AppDb,date:String,close:()->Unit){var code by remember{mutableStateOf("")};var invoice by remember{mutableStateOf("")};var qty by remember{mutableStateOf("")};var note by remember{mutableStateOf("")};val list=db.shipments(date);SimpleDialog("📦 Hàng xuất • $date",close){OutlinedTextField(code,{code=it},Modifier.fillMaxWidth(),label={Text("Mã hàng")});OutlinedTextField(invoice,{invoice=it},Modifier.fillMaxWidth(),label={Text("Invoice")});OutlinedTextField(qty,{qty=it},Modifier.fillMaxWidth(),label={Text("Số lượng")});OutlinedTextField(note,{note=it},Modifier.fillMaxWidth(),label={Text("Thiếu / nguyên nhân / đôn đốc")});Button(onClick={if(code.isNotBlank()){db.addShipment(Shipment(0,date,code,invoice,qty.toIntOrNull()?:0,"CHƯA XONG",note));code="";invoice="";qty="";note=""}},Modifier.fillMaxWidth()){Text("Thêm hàng xuất")};list.forEach{Text("• ${it.code} | ${it.invoice} | ${it.qty} | ${it.status} | ${it.note}")}}}
@Composable fun DataDialog(db:AppDb,date:String,close:()->Unit){var code by remember{mutableStateOf("")};var design by remember{mutableStateOf("")};var qty by remember{mutableStateOf("")};var note by remember{mutableStateOf("")};val list=db.data(date);SimpleDialog("💾 Hàng DATA • $date",close){OutlinedTextField(code,{code=it},Modifier.fillMaxWidth(),label={Text("Mã sản phẩm")});OutlinedTextField(design,{design=it},Modifier.fillMaxWidth(),label={Text("Mã thiết kế")});OutlinedTextField(qty,{qty=it},Modifier.fillMaxWidth(),label={Text("Số lượng")});OutlinedTextField(note,{note=it},Modifier.fillMaxWidth(),label={Text("Thiếu / nguyên nhân / nhắc xử lý")});Button(onClick={if(code.isNotBlank()){db.addData(DataRecord(0,date,code,design,qty.toIntOrNull()?:0,"CHƯA XONG",note));code="";design="";qty="";note=""}},Modifier.fillMaxWidth()){Text("Thêm DATA")};list.forEach{Text("• ${it.code} | TK ${it.design} | ${it.qty} | ${it.status} | ${it.note}")}}}
@Composable fun LotDialog(ctx:Context,db:AppDb,date:String,close:()->Unit){var lot by remember{mutableStateOf("")};var code by remember{mutableStateOf("")};var email by remember{mutableStateOf("")};var note by remember{mutableStateOf("")};val list=db.lots(date);SimpleDialog("📧 Chốt lô / báo cáo",close){OutlinedTextField(lot,{lot=it},Modifier.fillMaxWidth(),label={Text("Số lô")});OutlinedTextField(code,{code=it},Modifier.fillMaxWidth(),label={Text("Mã hàng")});OutlinedTextField(email,{email=it},Modifier.fillMaxWidth(),label={Text("Email nhận")});OutlinedTextField(note,{note=it},Modifier.fillMaxWidth(),label={Text("Nội dung báo cáo")});Button(onClick={if(lot.isNotBlank()){db.addLot(LotRecord(0,date,lot,code,"CHƯA CHỐT",email,note));lot="";code="";email="";note=""}},Modifier.fillMaxWidth()){Text("Lưu lô")};list.forEach{x->Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text("• Lô ${x.lot} | ${x.code} | ${x.status}");if(x.note.isNotBlank())Text(x.note)};TextButton(onClick={sendEmail(ctx,x.emailTo,"Báo cáo hoàn thành lô ${x.lot}","BÁO CÁO HOÀN THÀNH LÔ\nLô: ${x.lot}\nMã: ${x.code}\nNgày: ${x.date}\n${x.note}")}){Text("Mail")}}}}}
@Composable fun MailDialog(ctx:Context,db:AppDb,date:String,close:()->Unit){var subject by remember{mutableStateOf("")};var sender by remember{mutableStateOf("")};var note by remember{mutableStateOf("")};val list=db.mails(date);SimpleDialog("✉️ Theo dõi mail",close){OutlinedTextField(subject,{subject=it},Modifier.fillMaxWidth(),label={Text("Tiêu đề mail")});OutlinedTextField(sender,{sender=it},Modifier.fillMaxWidth(),label={Text("Người gửi / bộ phận")});OutlinedTextField(note,{note=it},Modifier.fillMaxWidth(),label={Text("Nội dung cần xử lý")});Button(onClick={if(subject.isNotBlank()){db.addMail(MailRecord(0,date,subject,sender,"CHƯA XỬ LÝ",note));subject="";sender="";note=""}},Modifier.fillMaxWidth()){Text("Lưu mail cần xử lý")};list.forEach{x->Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text("• ${x.subject}");Text("${x.sender} | ${x.status}");if(x.note.isNotBlank())Text(x.note)};OutlinedButton(onClick={sendEmail(ctx,"",x.subject,"Mail cần xử lý: ${x.subject}\nTừ: ${x.sender}\n${x.note}")}){Text("Mở mail")}}}}}

@Composable fun SimpleDialog(title:String,close:()->Unit,content:@Composable ColumnScope.()->Unit){AlertDialog(onDismissRequest=close,title={Text(title)},text={Column(Modifier.fillMaxWidth(),verticalArrangement=Arrangement.spacedBy(6.dp),content=content)},confirmButton={TextButton(onClick=close){Text("Đóng")}})}
@Composable fun HistoryScreen(db:AppDb,shift:String,refresh:Int){val dates=remember(refresh){db.historyDates()};var chosen by remember{mutableStateOf<String?>(null)};Column(Modifier.fillMaxSize().padding(12.dp)){Text("📅 Lịch sử",style=MaterialTheme.typography.headlineSmall);LazyColumn{items(dates){d->TextButton(onClick={chosen=d}){Text(d)}}}};chosen?.let{d->val ts=db.tasks(d,shift);AlertDialog(onDismissRequest={chosen=null},title={Text("$d • $shift")},text={Column{Text("Hoàn thành: ${ts.count{it.status=="HOÀN THÀNH"}}/18");Text("Có vấn đề: ${ts.count{it.problem}}");ts.filter{it.status!="HOÀN THÀNH"}.forEach{x->Text("• ${x.number}. ${x.title}: ${x.status}")}}},confirmButton={TextButton(onClick={chosen=null}){Text("Đóng")}})}}
@Composable fun OverviewScreen(tasks:List<DailyTask>,todos:List<Todo>,shift:String,overdue:Int,dueToday:Int){Column(Modifier.fillMaxSize().padding(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){Text("Tổng quan",style=MaterialTheme.typography.headlineSmall);Stat("Ca",shift);Stat("Hoàn thành","${tasks.count{it.status=="HOÀN THÀNH"}}/18");Stat("Đang làm","${tasks.count{it.status=="ĐANG LÀM"}}");Stat("Tồn đọng","${todos.count{it.status!="HOÀN THÀNH"}}");Stat("Đến hạn hôm nay","$dueToday");Stat("Quá hạn","$overdue")}}
@Composable fun Stat(a:String,b:String){Card(Modifier.fillMaxWidth()){Row(Modifier.padding(16.dp).fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text(a);Text(b,style=MaterialTheme.typography.titleMedium)}}}